Repository jenkinsci/theme-manager-plugin, pull requests merged in 2020-07, with the labels that each got.

#19 Updated README.md
  README.md
Labels: documentation

#20 Include release drafter on tags
  .github/workflows/release-drafter.yml
Labels: chore

#22 Fix user preferences loading
  src/main/java/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator.java
Labels: bug
