Repository jenkinsci/theme-manager-plugin, pull requests merged in 2025-01, with the labels that each got.

#281 Use `jenkins.baseline` to reduce bom update mistakes
  pom.xml
Labels: chore

#282 Refine theme manager
  pom.xml
  src/main/java/io/jenkins/plugins/thememanager/ThemeUserProperty.java
  src/main/java/io/jenkins/plugins/thememanager/none/NoOpThemeManagerFactory.java
  src/main/resources/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator/global.jelly
  src/main/resources/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator/global.properties
  src/main/resources/io/jenkins/plugins/thememanager/style/main.css
  src/main/resources/lib/theme-manager/selector.jelly
  src/main/resources/lib/theme-manager/selector.properties
Labels: enhancement

#284 Migrate from EE 8 to EE 9
  src/main/java/io/jenkins/plugins/thememanager/ThemeManagerPageDecorator.java
Labels: developer, internal
